version: "3"

services:
  # Create frontend container
  frontend:
    build: ./tuma-kitu-frontend
    restart: always
    container_name: frontend-docker
    ports:
      - "5000:5000"
  # Create backend container
  backend:
    # Create backend container
    build: ./tuma-kitu-backend
    ports:
      - "4000:4000"
    container_name: backend-docker
    restart: always
    volumes:
      - ./:/code
